# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "chichi"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = "3.1.8"
rodio = "0.15.0"
